const PDFDocument = require('pdfkit');
const fs = require('node:fs');
const path = require('node:path');

function getOutputDir() {
  const dir = process.env.PDF_OUTPUT_DIR || path.resolve(__dirname, '../../pdfs');
  return dir;
}

function initPdfEngine() {
  const dir = getOutputDir();
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
    console.log(`PDF output directory created: ${dir}`);
  }
  return dir;
}

function createDocument() {
  const doc = new PDFDocument({
    size: 'A4',
    margins: { top: 60, bottom: 60, left: 50, right: 50 },
    info: {
      Producer: 'V4V Agritech DPI',
      Creator: 'V4V Document Engine',
    },
  });
  return doc;
}

function addHeader(doc, title) {
  doc.fontSize(18).font('Helvetica-Bold').text('V4V Agritech DPI', { align: 'center' });
  doc.fontSize(10).font('Helvetica').text('Inclusive Agricultural Marketplace', { align: 'center' });
  doc.moveDown(0.5);
  doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#173c2d');
  doc.moveDown(1);
  doc.fontSize(14).font('Helvetica-Bold').text(title, { align: 'center' });
  doc.moveDown(1);
}

function addFooter(doc) {
  const bottom = doc.page.height - 60;
  doc.fontSize(8).font('Helvetica').fillColor('#666');
  doc.text(
    `Generated by V4V Document Engine | ${new Date().toISOString()}`,
    50, bottom,
    { align: 'center', width: 495 }
  );
}

function addFieldBlock(doc, label, value) {
  doc.fontSize(10).font('Helvetica-Bold').fillColor('#173c2d').text(`${label}:`, { continued: true });
  doc.font('Helvetica').fillColor('#000').text(`  ${value || 'N/A'}`);
}

function savePdf(doc, filename) {
  return new Promise((resolve, reject) => {
    const dir = getOutputDir();
    const filePath = path.join(dir, filename);
    const stream = fs.createWriteStream(filePath);
    doc.pipe(stream);
    doc.on('end', () => resolve(filePath));
    stream.on('finish', () => resolve(filePath));
    stream.on('error', reject);
    doc.end();
  });
}

function streamPdf(doc, res, filename) {
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `inline; filename="${filename}"`);
  doc.pipe(res);
  doc.end();
}

initPdfEngine();

module.exports = {
  createDocument,
  addHeader,
  addFooter,
  addFieldBlock,
  savePdf,
  streamPdf,
};
